### ISSUE TITLE
Add text.md scope to default scopes

### ISSUE THREAD

**Issue by adius** [fcrespo82/atom-markdown-table-formatter#39]
Just wasted my time on this one and I'm not the first one #37 .
Why is it not included?

**Comment by fcrespo82** [comment]
Because, as yourself pointed out, of #37.

The default scope for markdown in Atom is `source.gfm` and not `text.md`.

You could add `text.md` yourself using the preference we added exactly for that https://github.com/fcrespo82/atom-markdown-table-formatter#enable-markdown-table-formatter-for-the-current-file-type

Actually the [language-markdown](https://github.com/burodepeper/language-markdown) plugin tells in their [FAQ](https://github.com/burodepeper/language-markdown/blob/master/FAQ.md#spell-check-doesnt-work-how-do-i-enable-it) that the default spell-check will fail with it too. So it gives the steps to make it work with its plugin. It is exactly the same we are doing here.

**Comment by adius** [comment]
... uhm ... this didn't answer my question, or did it? 🤔

Why is it not included per default?

**Comment by fcrespo82** [comment]
As per Merrian Webster definition "https://www.merriam-webster.com/dictionary/default"

> default: 5  b :  a selection automatically used by a computer program **in the absence of a choice made by the user**
> &mdash; "Default." Merriam-Webster.com. Merriam-Webster, n.d. Web. 5 Jan. 2017. (emphasis added)

The installation of the `language-markdown` plugin was a choice made by the user, so adding its grammar `text.md` should be as well.

At least for me. But I may be biased as I don't use the plugin. Any of the collaborators @mDuo13 and @lierdakil want to give his opinion?

**Comment by adius** [comment]
I mean it doesn't hurt anyone to add it and it's unlikely that text.md will mean something different in the future and should therefore not be used

**Comment by lierdakil** [comment]
By the logic of "it doesn't hurt anyone to add it" we'd have to add all
possible Markdown scopes, and it opens a whole new can of worms of "why my
favorite obscure Markdown grammar doesn't work out of the box". Atom's
default Markdown grammar defines scope 'source.gfm'. Anything else is a
custom scope defined by third-party packages -- something we can't reliably
keep track of. So instead of trying to maintain an ever-chagning list of
scopes associated with Markdown, we instead include default Markdown scope,
and let the user decide if they want to add anything else. Does this make
sense?

чт, 5 янв. 2017 г. в 21:28, Adrian Sieber <notifications@github.com>:

I mean it doesn't hurt anyone to add it and it's unlikely that text.md will
mean something different in the future and should therefore not be used

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/fcrespo82/atom-markdown-table-formatter/issues/39#issuecomment-270718615>,
or mute the thread

**Comment by adius** [comment]
Well, the problem is that `source.gfm` is a pretty shitty default. It's just a very specific kind of markdown.
(The name already says it all: Github flavored markdown ... a brand name in the file format name ... really?)

`text.md` in comparison includes all flavors of markdown and I don't see it as a special scope.
Rather the most canonical scope!

**Comment by lierdakil** [comment]
Fact is, 'text.md' is not standard or universal. It is only used by a
single grammar package. Which is not included with Atom. Maybe it's a good
package, I don't know. But it's a single grammar package nonetheless. Some
other packages override 'source.gfm', and other still define more obscure
scopes ('source.academic', 'source.pfm', etc). As I said, a whole new can
of worms. Still, out of the box, Atom only has one Markdown scope and that
is 'source.gfm'.

P.S. I don't know what you mean by "canonicity", but I believe in the
absence of standards, it should be a majority vote. So, language-markdown
is donwloaded about 60k times. language-gfm, reportedly, is downloaded 300k
times. Which I don't even think is remotely large enough to be accurate,
since it's included with every Atom installation, but is still 5 times
greater.

пт, 6 янв. 2017 г. в 14:05, Adrian Sieber <notifications@github.com>:

**Comment by adius** [comment]
I don't share your thoughts on standards, but maybe we can agree on we should include what's important to a
lot and including the 2 biggest definitions sounds like the right thing to do.

**Comment by lierdakil** [comment]
Sorry, but the only thing I can personally agree to at this point is that README could use better wording to say that additional configuration is required with some community Markdown grammars. As I said, if we start including community packages into default configuration, we won't be able to stop, and we need to stop *somewhere*.

As a compromise, I guess we could make adding new grammar scopes to the configuration *easier*, f.ex. via 'Enable for current scope' command or somesuch. Would that be agreeable?

**Comment by adius** [comment]
I just had another idea.
How about we make the way of formatting a selection completely scope independent?
If someone selects a table and executes the command it doesn't matter at all which scope the document is, or does it?

**Comment by lierdakil** [comment]
When selection isn't empty, I guess it doesn't really matter. However, there's an issue of formatting *all* tables in the document if selection *is* empty (or on save). In that case, we don't want to mess about in random scopes, since something might *look* like a Markdown table, but in fact be something else, which we could mess up accidentally.

**Comment by adius** [comment]
Yeah, that's what I thought.
So no scope if there's a selection and only source.gfm if there's a selection. Good idea?

**Comment by lierdakil** [comment]
@adius, sorry it took so long, but I was preoccupied by other things at the moment, and then this just slipped my mind. See #40. It's kind of a mess, but you *may* want to add/change something in the readme (if you want a particular changeset for that, see https://github.com/fcrespo82/atom-markdown-table-formatter/pull/40/commits/282ead7cd107bc83f1b59759bebf5c8896a3f1e1)

@fcrespo82, if you could take a quick look at #40 and give me a go-ahead, that would be nice.

**Comment by lierdakil** [comment]
Published as v2.9.0 :tada:
